[profile.default]
src = "contracts"
test = "test"
out = "artifacts"
libs = ["lib"]
ignored_error_codes = ["license", "shadowing", "unused-return", "unused-param", "unused-var"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config